---
dist: trusty
language: ruby
cache: bundler
before_install:
  - bundle -v
  - rm -f Gemfile.lock
  - gem update --system
  - gem --version
  - bundle -v
script:
  - 'bundle exec rake $CHECK'
bundler_args: --without system_tests
rvm:
  - 2.5.1
env:
  global:
    - BEAKER_PUPPET_COLLECTION=puppet6 PUPPET_GEM_VERSION="~> 6.0"
stages:
  - test
  -
    if: tag =~ ^v
    name: deploy
matrix:
  fast_finish: true
  include:
    -
      env: CHECK="syntax lint metadata_lint check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop"
    -
      env: CHECK=parallel_spec
    -
      env: PUPPET_GEM_VERSION="~> 5.0" CHECK=parallel_spec
      rvm: 2.4.4
    -
      env: PUPPET_GEM_VERSION="~> 4.0" CHECK=parallel_spec
      rvm: 2.1.9
    -
      env: CHECK='build' DEPLOY_TO_FORGE=yes
      stage: deploy
branches:
  only:
    - master
    - /^v\d/
notifications:
  email: false
deploy:
  provider: puppetforge
  user: innogames
  password:
    secure: "u/ze96IcjdM627IJADJeVdNb33njyCfmmq5YnAqbL4GSRANTtmsNclZfh+JVzb3sAuRrm7VI11Ri4TlCuX4o/aSGPa7S7ROQFLHVfhWFqmS5Sa/sE3EoRdfyP90QYdaoYSiCfLPgnOhZrNpmhA+anhGvcdcZ5Zn/+IExB1r0mTaLAf2UqZrpdnNlot6zcCsH5qvGCsc0K1SWRFQMgW/7ThrPjXQoXGlJ/45ZjpDjlThu6ZHjJVSwp3d4o4lFZh/fycT0UfD0Yyd04R6pjXEeGp5txVv7lnC4zyawVVRZaWMEqorCeW/akKjVMaXlGxsRVMBpKDjhJRDOoBSpuqQWGJGB9DsqxShhkfV1gx8ofLNwOPW8to+M/Ykm4je7n/mre4B4ObPVb6aHvFIkb+Y4LMT/eLKnt03DnzWQJLTxCftFdBOozDv4p+efQp3rs8MacRLQe58uV4MCzUR72itR49IG4mNbdFJnpKcHwsvLeds+BLcnyBaHtqX7l8Iaam4KiIpWs0l1zaYa7X9SLkkisZq3VpkyQlLlVEQIFLE27aodYT0Ms9ATOZqPyIcUohx/Oe0T30foZ9+3Sb9yrteJdkf4cBbPUn2Ne6JXwefrEoozdHyi+pKcYjQy+LX0epM0hTfyGjnGupUWm2944oKwLf2YcixeNaZP6YJgSDnMeCc="
  on:
    tags: true
    all_branches: true
    condition: "$DEPLOY_TO_FORGE = yes"
